# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recambios import Recambios  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, recambios: List[Recambios]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param recambios: The recambios of this InlineResponse200.  # noqa: E501
        :type recambios: List[Recambios]
        """
        self.swagger_types = {
            'recambios': List[Recambios]
        }

        self.attribute_map = {
            'recambios': 'recambios'
        }
        self._recambios = recambios

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recambios(self) -> List[Recambios]:
        """Gets the recambios of this InlineResponse200.

        aray de recambios  # noqa: E501

        :return: The recambios of this InlineResponse200.
        :rtype: List[Recambios]
        """
        return self._recambios

    @recambios.setter
    def recambios(self, recambios: List[Recambios]):
        """Sets the recambios of this InlineResponse200.

        aray de recambios  # noqa: E501

        :param recambios: The recambios of this InlineResponse200.
        :type recambios: List[Recambios]
        """

        self._recambios = recambios
