# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.recambios_links_parent import RecambiosLinksParent  # noqa: F401,E501
from swagger_server import util


class RecambiosLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, parent: RecambiosLinksParent=None, _self: RecambiosLinksParent=None):  # noqa: E501
        """RecambiosLinks - a model defined in Swagger

        :param parent: The parent of this RecambiosLinks.  # noqa: E501
        :type parent: RecambiosLinksParent
        :param _self: The _self of this RecambiosLinks.  # noqa: E501
        :type _self: RecambiosLinksParent
        """
        self.swagger_types = {
            'parent': RecambiosLinksParent,
            '_self': RecambiosLinksParent
        }

        self.attribute_map = {
            'parent': 'parent',
            '_self': 'self'
        }
        self._parent = parent
        self.__self = _self

    @classmethod
    def from_dict(cls, dikt) -> 'RecambiosLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Recambios_links of this RecambiosLinks.  # noqa: E501
        :rtype: RecambiosLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parent(self) -> RecambiosLinksParent:
        """Gets the parent of this RecambiosLinks.


        :return: The parent of this RecambiosLinks.
        :rtype: RecambiosLinksParent
        """
        return self._parent

    @parent.setter
    def parent(self, parent: RecambiosLinksParent):
        """Sets the parent of this RecambiosLinks.


        :param parent: The parent of this RecambiosLinks.
        :type parent: RecambiosLinksParent
        """

        self._parent = parent

    @property
    def _self(self) -> RecambiosLinksParent:
        """Gets the _self of this RecambiosLinks.


        :return: The _self of this RecambiosLinks.
        :rtype: RecambiosLinksParent
        """
        return self.__self

    @_self.setter
    def _self(self, _self: RecambiosLinksParent):
        """Sets the _self of this RecambiosLinks.


        :param _self: The _self of this RecambiosLinks.
        :type _self: RecambiosLinksParent
        """

        self.__self = _self
